name: Deploy Docker on git release Tag with Image Retention (Self-Hosted Runner)

on:
  push:
    tags:
      - '[0-9]*.[0-9]*' # Matches tags like 0.1, 1.2, etc.

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy application
        run: |
          IMAGE_NAME=react_test
          CONTAINER_NAME=test_container
          
          # Stop and remove the old container
          docker ps -a -q --filter "name=$CONTAINER_NAME" | xargs -r docker rm -f

          # Remove older images beyond the retention limit (keep 3 older + current)
          docker images $IMAGE_NAME --format "{{.Repository}}:{{.Tag}} {{.CreatedAt}}" | \
          sort -rk 2 | \
          awk 'NR>3 {print $1}' | xargs -r docker rmi -f

          export TAG=${GITHUB_REF_NAME}
          TAG=${GITHUB_REF_NAME} docker compose build
          TAG=${GITHUB_REF_NAME} docker compose up -d --force-recreate
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}
